services:
  - type: web
    name: scamguard-api
    env: python
    region: oregon
    plan: free

    pythonVersion: 3.11.9

    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
